'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

    '''<summary>
    '''LabelComputerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelComputerName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelIP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelKioskName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelKioskName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ButtonAddKiosk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonAddKiosk As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ButtonAddKioskCookie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonAddKioskCookie As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''PanelAddNewKiosk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelAddNewKiosk As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TextBoxKiosk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxKiosk As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ListBoxPrinter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListBoxPrinter As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''TextBoxHostName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxHostName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ListBoxLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListBoxLine As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''TextBoxIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxIP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonAddNewSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonAddNewSubmit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GridViewFullDataset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewFullDataset As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ObjectDataSourceFullDataset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ObjectDataSourceFullDataset As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
